---
title: antrusd.me
#description: 'Anthony Rusdi'
#baseurl: '/tale'
url: 'https://antrusd.me'

markdown: kramdown

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate

permalink: /:year-:month-:day/:title
paginate: 5

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - tale.gemspec
